name: Build Pisscou Store

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Pisscou Store build started"
          mkdir -p output
          echo "Pisscou Store"
          > output/README.txt
